# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version=1.8.0-beta.2
maven_group=de.tomalbrc
archives_base_name=filament

# Dependencies
fabric_version=0.160.5+26.3
# https://github.com/Patbox/Polymer/releases/
polymer_version=0.18.0+26.3-rc-1
bil_version=2.2.0+26.3-rc-3
# https://github.com/Patbox/TextPlaceholderAPI/releases
papi_version=3.1.0-beta.1+26.2
# https://github.com/Patbox/sgui/releases
sgui_version=2.2.0+26.3

curseforge_project_id=1118465