[book]
authors = ["tomalbrc"]
language = "en"
#multilingual = false
src = "src"
title = "Filament Documentation (1.4.x)"

# we be using mdbook

[preprocessor.langtabs]
command = "mdbook-langtabs"

[output]

[output.html]
additional-css = ["./custom.css", "langtabs.css"]
additional-js = ["langtabs.js"]

[output.html.fold]
enable = true
level = 1
